### ISSUE TITLE
Error when performing multiple withdrawals

### ISSUE THREAD

**Issue by alvaro-ricotta** [rio-org/validator-ejector#2]
![image](https://github.com/rio-org/validator-ejector/assets/81116391/0b71b44c-f6bd-4227-88db-9ed88628252b)

The process was as follows, I made multiple re-stakes with my account 0xD63d4235f9AE67108718C0A2dAffE7BE85721BFf, after the term was fulfilled, I carried out several withdrawal processes and some interesting things happened. The first problem I encountered is that some withdrawals and claims were processed quickly, but the first withdrawal took almost 2 days to allow me to make the claim.

On the other hand, the last withdrawal was made with 3 consecutive withdrawals but all were processed as one. That being said, I don't know if the bug in question is that I shouldn't have been able to perform the withdrawal 3 times in a row, or if they should have been processed as 3 different withdrawals, it would be necessary to analyze what happened along the way.

**Comment by solimander** [comment]
Thanks for the report @alvaro-ricotta!

> The process was as follows, I made multiple re-stakes with my account 0xD63d4235f9AE67108718C0A2dAffE7BE85721BFf, after the term was fulfilled, I carried out several withdrawal processes and some interesting things happened. The first problem I encountered is that some withdrawals and claims were processed quickly, but the first withdrawal took almost 2 days to allow me to make the claim.

Depending on the time left until the next rebalance, there may be inconsistencies in the timing between withdrawal requests and claims, though it should not be as long as 2 days - I'll have a look at that.

> On the other hand, the last withdrawal was made with 3 consecutive withdrawals but all were processed as one. That being said, I don't know if the bug in question is that I shouldn't have been able to perform the withdrawal 3 times in a row, or if they should have been processed as 3 different withdrawals, it would be necessary to analyze what happened along the way.

Multiple withdrawal requests within the same period get batched into a single claim to reduce costs, so that is expected.

This is a repository intended for issues relating the validator exit automation, so I am going to close this for now. I will report back with any updates to the first issue you raised.

**Comment by alvaro-ricotta** [comment]
Hello, I also sent you a problem with an issue related to decimals. I believe you should check it. Thank you for clarifying that this is not the repo to report this, but it's very complicated to find answers, whether on GitHub, Gmail, or through form types.
